--- 
abstract: Timestamp subtypes for Moose classes
author: Sam Vilain <samv.org>
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: MooseX-Timestamp
no_index: 
  directory: 
    - inc
    - t
requires: 
  Memoize: 0
  Moose: 0.32
  Sub::Exporter: 0
  perl: 5.6.0
version: 0.02
